### ISSUE TITLE
Composition and Aggregation

### ISSUE THREAD

**Issue by DylandeWit** [glesica/dcdg.dart#12]
Sorry if I'm missing something but does it currently have no support for Composition and Aggregation? It generates just extents for me. No has-a relationships.

**Comment by glesica** [comment]
That's correct. I wanted to implement some filtering first, otherwise any non-trivial package resulted in a diagram that was too busy to be useful (at least to me). It wouldn't be hard to add, however. I'll look into it this evening.

**Comment by glesica** [comment]
OK, I think that should be good to go. I still need to fix https://github.com/glesica/dcdg.dart/issues/13, though. Until then you'll see double relationships (and fields) for classes that are named in an `export` declaration.

**Comment by DylandeWit** [comment]
Perfect, thank you!
