### ISSUE TITLE
Can't Import Package

### ISSUE THREAD

**Issue by dodyac** [glesica/dcdg.dart#18]
![Screenshot (75)](https://user-images.githubusercontent.com/37199748/57941941-70bb7000-78fa-11e9-9cba-8c97c322650d.png)

**Comment by georgelesica-wf** [comment]
You aren't even showing the error message. I can't debug that without more information. Also, I'm not sure you want to use DCDG as a library like that, it's intended to be used as a command line tool.

**Comment by dodyac** [comment]
how to export to class diagram?

**Comment by georgelesica-wf** [comment]
You can run `pub run dcdg` inside of a Dart project to print out the PlantUML markup. There are many options for customizing the diagram, see `pub run dcdg --help` or the USAGE file. You can also take a look at `tools/docs.sh` for an example of how I run DCDG against itself to generate the diagram found in the README.
