### ISSUE TITLE
How to save to png file?

### ISSUE THREAD

**Issue by Zeyad-A-Ramadan** [glesica/dcdg.dart#22]
i run the command "pub global run dcdg --output=ClassDiagram.png". I can't find the command to save as png written anywhere not even in help

**Comment by patkujawa-wf** [comment]
This tool doesn't export to PNG. It does allow you to output to PUML (and others), and then you can use PlantUML to create a PNG if you want.

There are too many options for exporting to a still image to support them all in a tool that's primarily focused on getting the class diagram information extracted from code and into any usable format. Perhaps in the future someone will add a simple PNG output option, but I don't foresee that happening.

You can pipe from `dcdg` directly to plantuml to create a PNG by, e.g., `dcdg | plantuml -pipe > "temp.png"`
