### ISSUE TITLE
Does this work Recursively/Hierarchically?

### ISSUE THREAD

**Issue by psygo** [glesica/dcdg.dart#23]
I wanted to run this CLI on a folder which has a bunch of my packages, but couldn't because it seems to only work within the context of a single package. Am I wrong?

Anyway, I didn't know how to create Dart CLIs so I took it as an opportunity to learn something new. I worked out a CLI that looks for packages and then calls `dcdg` on each to generate their UMLs &mdash; it does so by calling out a process on a shell, instead of using the `dcdg` Dart package itself, I was a bit lazy...

You can check out the package [here](https://github.com/psygo/generate_uml) &mdash; basically I called a package everything that has a `lib` folder inside, it makes sense to my folder's context, but it is probably not a universal solution of course.

This is an awesome package and I would like to help if I can, let me know if this idea interests you.

Another suggestion I have is for a feature of drawing UML for relationships between packages, which can be very important for understanding the larger scope projects. Does the `dcdg` package already do that?

**Comment by glesica** [comment]
That’s a cool idea! I have another half-finished project that visualizes Dart dependencies that might be able to be reused for the package relationships, at least in part.

**Comment by psygo** [comment]
Some months ago I found the [pubviz](https://pub.dev/packages/pubviz) package, which takes care of visualizing these relationships as well, however the focus there is actually on versioning. But maybe there is something useful in their code. I orginally found out about it from [Kevin Moore's presentation on DartConf 2018](https://youtu.be/oimGULseQ4M).
