### ISSUE TITLE
Not seeing all classes export to Plantuml

### ISSUE THREAD

**Issue by darrinps** [glesica/dcdg.dart#26]
This might be an issue with Plantuml instead of this tool, but when I run plantuml against a .puml file generated by this tool, much of the .png seems to be missing. There are connection lines that go off the edge that I think should lead to the missing classes. 

Again, not sure if PlantUML is at fault or this tool isn't generating things correcly.

**Comment by patkujawa-wf** [comment]
You can check the .puml file to see if anything is missing. I bet you're running into the image size limits. You can change `PLANTUML_LIMIT_SIZE` to increase those. See https://plantuml.com/faq for example.

**Comment by darrinps** [comment]
Thanks! I'll give that a try.

**Comment by darrinps** [comment]
That was it. Thanks!
