### ISSUE TITLE
"Unhandled exception:" error

### ISSUE THREAD

**Issue by mzamayias** [glesica/dcdg.dart#30]
I'm always getting the following output when running dcdg:

>Unhandled exception:
>FileSystemException: Directory listing failed, path = '/home/mzamayias/Documents/Repositories/glowing-sniffle/Current Courses/Agile Programming/Assignments/Assignment 2/dart/simple_hearts_game/lib/' (OS Error: No such file or directory, errno = 2)
>#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:37:68)
>#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
>#2      findClassElements (package:dcdg/src/find_class_elements.dart:35:8)
>#3      main (file:///home/mzamayias/.pub-cache/hosted/pub.dartlang.org/dcdg-2.0.1/bin/dcdg.dart:28:25)
>#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
>#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Am I doing something wrong? I've followed the [instructions](https://pub.dev/packages/dcdg/install) for installation and usage. Also, as this my first Issue report on GitHub, am I doing it right?

**Comment by glesica** [comment]
Interesting. Could you try it on a path that doesn't have any spaces? I've seen Dart get cranky about that before.

**Comment by mzamayias** [comment]
I've copied the project to `Desktop/` and tried `dcdg  -o 'uml.puml'` and `pub global run dcdg -o 'uml.puml'` with both giving the same `Unhandled exception: FileSystemException: Directory listing failed`.

I'm checking again how to use `dcdg` and I'm curious, on which file should I import the package, on all of them or just on the "main".dart? Could this cause the error?

**Comment by glesica** [comment]
Oh, I think I see. You don't import DCDG into your project, you run it on your source code. Do you have a `lib/` directory in your project? DCDG assumes that you are using a standard Dart package layout, which includes a `lib/` directory (where your code lives).

**Comment by mzamayias** [comment]
Turns out my project was not in a package layout. After some tinkering I had a Dart package that would run successfully, then tried `pub global run dcdg -o 'uml.puml'` and voilà, I had the `uml.puml` for my classes. Thanks a lot!
