### ISSUE TITLE
Better documentation on exclude

### ISSUE THREAD

**Issue by tiloc** [glesica/dcdg.dart#33]
I am trying to exclude any Flutter SDK packages from the output. I have tried a lot of variations:
--exclude=^flutter.*
--exclude=flutter.*
--exclude=StatefulWidget
--exclude=.*StatefulWidget

none of these seem to have any effect. I am looking for better documentation on such a use-case and maybe a --verbose option for dcdg that prints out whether it believes something is a match. It is unclear to me whether the package names, such as flutter:: are part of the class name that needs to match.

I have also attempted the --exported-only option as an alternative, but that leads to broken output with numerous repeating fields.

**Comment by glesica** [comment]
Most of the exclude stuff hasn't yet been implemented. Take a look at https://github.com/glesica/dcdg.dart/issues/1 for status. Right now it only works on class names. I'll take a look at the `--exported-only`, there might be a bug there.

**Comment by glesica** [comment]
What's broken about the output when using `--exported-only`?

**Comment by tiloc** [comment]
I get to see the same field name several times.
I have spent the past 2 hours or so familiarising myself with the package and adding some better exclude functionality plus a new "--verbose" parameter. Will show you my PR probably later today, currently making sure the tests run.

**Comment by glesica** [comment]
Can we close this? It seems as though #1 captures the rest of the issues here that weren't fixed by #34.
