### ISSUE TITLE
Mehtod "accept" was call on null error!!

### ISSUE THREAD

**Issue by TAMU73** [glesica/dcdg.dart#35]
I followed your documentation but it's not working. It always says accept was call on null
![image](https://user-images.githubusercontent.com/47109205/115202101-c2d42400-a115-11eb-9d8f-09067f4f795e.png)

**Comment by glesica** [comment]
I don't see DCDG anywhere in that stack trace, are you sure you included the entire thing? Also, are you running it from the top-level of your Dart package? In other words, is there a `pubspec.yaml` file in that directory?

**Comment by glesica** [comment]
Closing because no response from the reporter.
