### ISSUE TITLE
exclude samples

### ISSUE THREAD

**Issue by jorwan** [glesica/dcdg.dart#36]
Where can I find some samples using exclude param from cli ?

I would like to exclude dart and flutter native classes (the one I didn't create)
Because after generate uml class diagram, it comes with Color flutter class and others I didn't create.

How can I ignore them ? I just want to generate all the classes I create only.

Thanks

**Comment by glesica** [comment]
You should be able to pass `--exclude flutter` since "flutter" will be in the full name of any type that comes from the Flutter library.

**Comment by glesica** [comment]
Feel free to re-open if you're still having trouble.
