### ISSUE TITLE
plantuml.com gives "Forbidden" error on dcdg output

### ISSUE THREAD

**Issue by zathras** [glesica/dcdg.dart#38]
Hi George,

I got this error form www.plantuml.com with some dcdg output:
```
Forbidden

You don't have permission to access /plantuml/uml/xLrVSzmuSd_tfs3fwRQypaFkwYgbygrE6icxa_CVdINlfl8oHP6O6Pmuu0G4nz8w_ku1-2Cez0Ya6l8uLwdAYqHsDngDxaRZ3ngSlpOcrwRTL2yQOJALRqIppGjn9RQvpasji-FZ5o-AAc-QxEWVzKxcrQBPhOwFotprBwKjUNnyLUHLVbE9-IPVYVDyTPHzUP5bhzxAnho-cdyKgXJQuN_A5dfuQIp9Ir8o-opD-htu_AiKdxUrDd_umP7iQbbcsrmgCrlBgh

(plus another page of goop)
```

Is this interesting enough to you that you'd like me to dig up a reproducible case?  Or is the plantuml website not all that reliable to begin with?

If this is of interest, I'm happy to put a more reasonable bug report together.  The example that creates this is the opposite of minimal -- I just ran `dcdg` on about 5KLOC, did a copy-paste, got the error, then went back to umlet and digging through dartdoc output :-). But I'm happy to spend a bit of time putting together a usable bug report, if you don't mind a largeish example (34K puml file).  In this case, I might hold off for a couple of days, while I do a bit of refactoring prior to making the github repo public, since maybe you'd want access to the code that created it?

FWIW I use generics a fair bit, including generic methods.  Might be totally unrelated, but maybe generic methods aren't all that commonly used in Dart?

**Comment by glesica** [comment]
That looks like a problem of some kind with plantuml.com. Maybe try it with the PlantUML command line tool and see if that works?

**Comment by glesica** [comment]
Closing this since the reporter didn't follow up and I suspect it was an error in the PlantUML web app.
