### ISSUE TITLE
package choosing 

### ISSUE THREAD

**Issue by killerm250m** [glesica/dcdg.dart#40]
when I run the command it generates UML for the whole application how I can select a package that I want to generate from it?

**Comment by glesica** [comment]
It generates UML for the package you run it on. If you run it on your application (which, in Dart, is just a package) then you get UML for that. If you want to run it against a different package, you'll want to clone the repo for that package and run DCDG against it. If you just want to run it against part of your application, then you can use the `--include` and `--exclude` options to filter the output.
