### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by fredgrott** [glesica/dcdg.dart#41]
Have an error when attempting to generate diagrams for this repo: https://github.com/fredgrott/dart_oop_patterns

PS D:\fredgrttsstuff\GithubProjects\dart_oop_patterns\abstract_factory> flutter pub global run dcdg -s bin -o reports/docs/diagrams/src
Unhandled exception:
Bad state: Unable to find the context to D:\fredgrttsstuff\GithubProjects\dart_oop_patterns\abstract_factory\bin\abstract_factory.dart
#0      AnalysisContextCollectionImpl.contextFor (package:analyzer/src/dart/analysis/analysis_context_collection.dart:89:5)
#1      findClassElements (package:dcdg/src/find_class_elements.dart:44:39)
#2      main (file:///D:/fluttersdk/myfluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/dcdg-3.1.1/bin/dcdg.dart:35:25)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
pub finished with exit code 255

**Comment by glesica** [comment]
I'm able to reproduce this with a greatly reduced test case. My guess is that I just need to tell the analyzer to look at the `bin/` directory. I'll look into it.
