### ISSUE TITLE
update dependencies in pubspec to latest versions

### ISSUE THREAD

**Issue by itadminmynapse** [glesica/dcdg.dart#44]
I get errors about version solving failed when including dcdg in my project. Reason is that the dependency versions in the pubspec are outdated.
for example: analyzer is already at version 2.4.0 (is still at 1.1.0)
version of test package is now at 1.18.2 (is still at 1.0.0)

Any plans to upgrade to latest dependeny packages?

**Comment by fredgrott** [comment]
one can do that via dependency overrides of course
