### ISSUE TITLE
How to get UML diagram for only the lib folder

### ISSUE THREAD

**Issue by nyck33** [glesica/dcdg.dart#46]
I have it working for Flutter but for large projects the resulting UML is too complex since packages are included. 
Is there a way to get a UML just for the lib folder?
I tried running from the lib folder but it changes the CWD to project root and then I get the same diagram.

**Comment by nyck33** [comment]
Does using `--include appname*` do the same thing?

**Comment by nyck33** [comment]
It did not work.  I also tried targeting a specific package with 
` --exclude '^flutter::[a-zA-Z]+::[a-zA-Z]+::[a-zA-Z]+.dart::[a-zA-Z]+'` for `flutter::src::widgets::framework.dart::StatefulWidget` but that did not work either.  I am still getting the full UML with flutter packages, other packages and lib.

**Comment by nyck33** [comment]
@glesica Thanks for getting back to me.  I'll ask the project leader about sharing.

**Comment by nyck33** [comment]
@glesica Here is a open source project similar to what I usually try to build using Riverpod and  Freezed: https://github.com/aqwert/riverpod_crud

I tried 
```
flutter pub run dcdg -o uml/ex-flutter.puml --exclude '^flutter'
```
but get
```
Unhandled exception:
Bad state: Unable to find the context to /media/nobu/NTFSUbuWin/1_TAP/FlutterGithub/Riverpod_Freezed/riverpod_crud/lib/data/dated_identity_data.freezed.dart
#0      AnalysisContextCollectionImpl.contextFor (package:analyzer/src/dart/analysis/analysis_context_collection.dart:89:5)
#1      findClassElements (package:dcdg/src/find_class_elements.dart:44:39)
<asynchronous suspension>
#2      main (file:///home/nobu/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/dcdg-3.1.1/bin/dcdg.dart:35:19)
<asynchronous suspension>
```
Ideally I want to get a UML diagram of just what's in this repo, excluding Flutter packages so I can see how this app is "wired up".  

Btw your blog is helpful for those new to your package: https://goto10line.net/2019/05/25/automatic-uml-diagrams-for-dart/

**Comment by glesica** [comment]
Hmm, I'm really not sure why it would fail on that file. I have a test fixture that uses parts, so it's unlikely to be that. Maybe it's trying to read the part before the main file?

**Comment by glesica** [comment]
Oh, I see, the `.freezed.dart` files are excluded in `analysis_options.yaml`, so the analyzer ignores them and then DCDG asks the analyzer for a context, which it doesn't have. For now, you can remove the exclude lines related to the `lib/` directory from `analysis_options.yaml` before you run DCDG. When I have time, I'll add some checking to make sure DCDG doesn't try to read an un-analyzed file (or can recover when it does).

**Comment by nyck33** [comment]
I'm sorry to have taken up your valuable time like that.  Thanks for helping.

**Comment by nyck33** [comment]
It worked on riverpod_crud!  But not on the app that lead to this posting originally so maybe it's an outdated Flutter version issue?  It's unneeded now anyways, managed to convince the boss to let me work in the greenfield.  Thanks for your help!

**Comment by nyck33** [comment]
Just realized some connecting lines are missing though.  For example from state notifiers of Riverpod, none of them connect to anything else.  Here in the top right are the state notifiers (act as controllers in MVC-type app structure): https://drive.google.com/file/d/1FuYjpxUoDyi0qTZQon4HkxNq3sjFSWWs/view?usp=sharing .  They each have a state and that state is one of the models at the very left of the image but nothing connects them.  It feels like there is a "state notifier A has a model x" relationship.
