### ISSUE TITLE
Bug: Duplicated fields when using 'part' keyword in dart

### ISSUE THREAD

**Issue by XavierChanth** [glesica/dcdg.dart#50]
Discovered this bug because I am using the package [json_serializable](https://pub.dev/packages/json_serializable).

When using the dart 'part' and 'part of' keywords, the class' fields, methods, and relationships get duplicated.

For example:
If I break a file into 2 parts, then everything in the diagram is doubled for that class.
If I break a file into 3 parts, then everything in the diagram is tripled for that class.

Example Code:
```dart
// file_a.dart
import 'file_b.dart';

part 'file_a2.dart';

class A extends B {
  final String _name;

  A(this._name);

  String get name => _getName(this);
}
```
```dart
//file_a2.dart
part of 'file_a.dart';

String _getName(A instance) => instance._name;
```
```dart
//file_b.dart
class B {}
```

Creates this diagram:
![image](https://user-images.githubusercontent.com/33691921/148608102-2817b666-8d47-44e2-9805-14c6aa6c4395.png)

**Comment by glesica** [comment]
Interesting! Probably an easy fix, I'll take a look over the weekend.

**Comment by XavierChanth** [comment]
Cheers!
