### ISSUE TITLE
Add support for Mermaid

### ISSUE THREAD

**Issue by glesica** [glesica/dcdg.dart#54]
It would be cool to be able to output diagrams to Mermaid format since that tool is quite popular / useful.

See: <http://mermaid-js.github.io>

**Comment by plumsky** [comment]
@glesica 
When this https://github.com/glesica/dcdg.dart/pull/56 will be merge to master?

**Comment by glesica** [comment]
Once I've had time to address the outstanding issues described in the PR.

**Comment by bperreault** [comment]
I took this branch that has the mermaid option. It was very useful in diagramming my mobile app.  I found there were a few lines that I had to remove from the generated code to allow the graph to be displayed but overall excellent to have this. Thank you.

**Comment by glesica** [comment]
This is done.
