### ISSUE TITLE
Report crash on package without pub get

### ISSUE THREAD

**Issue by glesica** [glesica/dcdg.dart#8]
The visitor barfs if an export uses a `package:` style URI rather than a relative path. Seems like it might be an analyzer bug (it may have something to do with https://github.com/dart-lang/sdk/issues/35174), but noting it here for the future. Example stack trace:

```
 dcdg --exported-only
file:///home/george/w_common/lib/disposable.dart
{DisposableManager, DisposableManagerV2, DisposableManagerV3, DisposableManagerV4, DisposableManagerV5, DisposableManagerV6, DisposableManagerV7, ObjectDisposedException}
Unhandled exception:
NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept<void>(Instance of 'ClassElementCollector')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      ClassElementCollector.visitExportElement (package:dcdg/src/class_element_collector.dart:47:29)
#2      ExportElementImpl.accept (package:analyzer/src/dart/element/element.dart:4668:53)
#3      ElementImpl.safelyVisitChildren (package:analyzer/src/dart/element/element.dart:3616:15)
#4      LibraryElementImpl.visitChildren (package:analyzer/src/dart/element/element.dart:6604:5)
#5      RecursiveElementVisitor.visitLibraryElement (package:analyzer/dart/element/visitor.dart:265:13)
#6      LibraryElementImpl.accept (package:analyzer/src/dart/element/element.dart:6488:53)
#7      findClassElements (package:dcdg/src/find_class_elements.dart:49:33)
<asynchronous suspension>
#8      main (file:///home/george/dcdg.dart/bin/dcdg.dart:28:25)
<asynchronous suspension>
#9      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by glesica** [comment]
Turns out I'd just forgotten to `pub get` in the package I was running against. So this isn't a bug, but it might be nice to catch this and suggest running `pub get` since that seems like a likely thing to be forgotten now and again.

**Comment by Nicolaidam** [comment]
Hi, So i just got the same error. What do you mean with "Turns out I'd just forgotten to pub get in the package I was running against."? 
I've tried running flutter pub get dcdg and afterwards flutter pub run dcdg and i still get the error. 
I use visual studio btw.

**Comment by glesica** [comment]
You don't need to add DCDG as a dependency of your project, it just needs to be installed somehow (usually `pub global activate dcdg`). But the package you want to run it against needs to have its dependencies fetched. So if you have a package called `foo` that you want a class diagram for, you need to have run `pub get` (or `flutter pub get` if you're using Flutter) in the `foo` package before you run DCDG.

**Comment by Nicolaidam** [comment]
1) So the first thing i do in installing DCDG with the command flutter pub global activate dcdg (since i use flutter) in the main folder of my project.
![image](https://user-images.githubusercontent.com/32563707/111127316-f8fd1180-8573-11eb-8de6-614ffb660ea1.png)
2) I want to make a class diagram of my Main.dart file, so I move to the "lib" folder and executes the command flutter pub get.
![image](https://user-images.githubusercontent.com/32563707/111127724-6d37b500-8574-11eb-92ee-c468d7c26bc6.png)
3) I run the command pub global run dcdg in the Lib folder and getting following result:
![image](https://user-images.githubusercontent.com/32563707/111127974-aec86000-8574-11eb-8398-dbc199c0354d.png)

So it seems the pack is not installed correctly.. I'm sorry if I do a stupid mistake, im pretty new with Flutter so please bear with me. Hope you can help me, and have a great day!

**Comment by glesica** [comment]
You run DCDG from the root of your project (where your `pubspec.yaml` is). It runs against a Dart package, not an individual file.

**Comment by Nicolaidam** [comment]
Okay, but when I run "flutter pub global run dcdg" from the main folder I get this error:

**Nicolais-MacBook-Pro:acdc_flutter_app nicolai$ flutter pub global activate dcdg**
Package dcdg is currently active at version 2.0.1.
Resolving dependencies...
+ analyzer 0.36.4 (1.1.0 available)
+ args 1.6.0 (2.0.0 available)
+ async 2.4.2 (2.5.0 available)
+ charcode 1.1.3 (1.2.0 available)
+ collection 1.14.13 (1.15.0 available)
+ convert 2.1.1 (3.0.0 available)
+ crypto 2.1.5 (3.0.0 available)
+ csslib 0.16.2 (0.17.0 available)
+ dcdg 2.0.1
+ file 5.2.1 (6.1.0 available)
+ front_end 0.1.19 (0.1.29 available)
+ glob 1.2.0 (2.0.0 available)
+ html 0.14.0+4 (0.15.0 available)
+ intl 0.16.1 (0.17.0 available)
+ js 0.6.2 (0.6.3 available)
+ kernel 0.3.19 (0.3.29 available)
+ meta 1.2.4 (1.3.0 available)
+ node_interop 1.2.1
+ node_io 1.2.0
+ package_config 1.9.3 (2.0.0 available)
+ path 1.7.0 (1.8.0 available)
+ pedantic 1.9.2 (1.11.0 available)
+ pub_semver 1.4.4 (2.0.0 available)
+ source_span 1.7.0 (1.8.1 available)
+ string_scanner 1.0.5 (1.1.0 available)
+ term_glyph 1.1.0 (1.2.0 available)
+ typed_data 1.2.0 (1.3.0 available)
+ watcher 0.9.7+15 (1.0.0 available)
+ yaml 2.2.1 (3.1.0 available)
Precompiling executables...
Precompiled dcdg:dcdg.
Installed executable dcdg.
Warning: Pub installs executables into $HOME/Documents/flutter/.pub-cache/bin, which is not on your path.
You can fix that by adding this to your shell's config file (.bashrc, .bash_profile, etc.):

  export PATH="$PATH":"$HOME/Documents/flutter/.pub-cache/bin"

Activated dcdg 2.0.1.
**Nicolais-MacBook-Pro:acdc_flutter_app nicolai$ flutter pub get**
Running "flutter pub get" in acdc_flutter_app...                    0,5s
**Nicolais-MacBook-Pro:acdc_flutter_app nicolai$ flutter pub global run dcdg**
Unhandled exception:
NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept<DartObjectImpl>(Instance of 'ConstantVisitor')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ConstantEvaluationEngine.evaluateConstructorCall (package:analyzer/src/dart/constant/evaluation.dart:717:53)
#2      ConstantVerifier.visitInstanceCreationExpression (package:analyzer/src/dart/constant/constant_verifier.dart:131:27)
#3      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6111:15)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7687:20)
#5      ListLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6842:15)
#6      RecursiveAstVisitor.visitListLiteral (package:analyzer/dart/ast/visitor.dart:1045:10)
#7      ConstantVerifier.visitListLiteral (package:analyzer/src/dart/constant/constant_verifier.dart:145:11)
#8      ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6837:49)
#9      NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7446:18)
#10     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1075:10)
#11     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7441:49)
#12     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7687:20)
#13     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:378:16)
#14     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:625:10)
#15     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:374:49)
#16     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6199:20)
#17     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:991:10)
#18     ConstantVerifier.visitInstanceCreationExpression (package:analyzer/src/dart/constant/constant_verifier.dart:139:13)
#19     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6111:15)
#20     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7446:18)
#21     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1075:10)
#22     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7441:49)
#23     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7687:20)
#24     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:378:16)
#25     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:625:10)
#26     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:374:49)
#27     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6199:20)
#28     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:991:10)
#29     ConstantVerifier.visitInstanceCreationExpression (package:analyzer/src/dart/constant/constant_verifier.dart:139:13)
#30     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6111:15)
#31     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7687:20)
#32     ListLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6842:15)
#33     RecursiveAstVisitor.visitListLiteral (package:analyzer/dart/ast/visitor.dart:1045:10)
#34     ConstantVerifier.visitListLiteral (package:analyzer/src/dart/constant/constant_verifier.dart:145:11)
#35     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6837:49)
#36     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7446:18)
#37     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1075:10)
#38     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7441:49)
#39     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7687:20)
#40     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:378:16)
#41     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:625:10)
#42     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:374:49)
#43     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6199:20)
#44     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:991:10)
#45     ConstantVerifier.visitInstanceCreationExpression (package:analyzer/src/dart/constant/constant_verifier.dart:139:13)
#46     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6111:15)
#47     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8655:18)
#48     RecursiveAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:1160:10)
#49     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8651:49)
#50     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7687:20)
#51     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1121:17)
#52     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:667:10)
#53     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1117:49)
#54     IfStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5704:21)
#55     RecursiveAstVisitor.visitIfStatement (package:analyzer/dart/ast/visitor.dart:967:10)
#56     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5699:49)
#57     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7687:20)
#58     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1121:17)
#59     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:667:10)
#60     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1117:49)
#61     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1076:13)
#62     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:673:10)
#63     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1072:49)
#64     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5016:12)
#65     RecursiveAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:919:10)
#66     ConstantVerifier.visitFunctionExpression (package:analyzer/src/dart/constant/constant_verifier.dart:115:11)
#67     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5010:49)
#68     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4869:26)
#69     RecursiveAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:907:10)
#70     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4862:49)
#71     FunctionDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4910:27)
#72     RecursiveAstVisitor.visitFunctionDeclarationStatement (package:analyzer/dart/ast/visitor.dart:913:10)
#73     FunctionDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4906:15)
#74     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7687:20)
#75     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1121:17)
#76     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:667:10)
#77     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1117:49)
#78     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1076:13)
#79     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:673:10)
#80     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1072:49)
#81     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7127:12)
#82     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1057:10)
#83     ConstantVerifier.visitMethodDeclaration (package:analyzer/src/dart/constant/constant_verifier.dart:163:11)
#84     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7118:49)
#85     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7687:20)
#86     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1590:13)
#87     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:703:10)
#88     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1560:49)
#89     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7687:20)
#90     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2167:21)
#91     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:727:10)
#92     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2146:49)
#93     LibraryAnalyzer._computeConstantErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:246:10)
#94     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:402:5)
#95     LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:172:9)
#96     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#97     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:171:13)
#98     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#99     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:170:34)
#100    LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:111:14)
#101    _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#102    LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:110:43)
#103    AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1451:63)
#104    PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#105    AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1428:20)
#106    AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1100:33)
<asynchronous suspension>
#107    AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2188:24)
<asynchronous suspension>
#108    AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2118:5)
#109    ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:77:17)
#110    new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:46:36)
#111    findClassElements (package:dcdg/src/find_class_elements.dart:26:29)
#112    main (file:///Users/nicolai/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/dcdg-2.0.1/bin/dcdg.dart:28:25)
#113    _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#114    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1487:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1428:20)
#3      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1100:33)
<asynchronous suspension>
#4      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2188:24)
<asynchronous suspension>
#5      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2118:5)
#6      ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:77:17)
#7      new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:46:36)
#8      findClassElements (package:dcdg/src/find_class_elements.dart:26:29)
#9      main (file:///Users/nicolai/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/dcdg-2.0.1/bin/dcdg.dart:28:25)
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
**pub finished with exit code 255**

**Comment by glesica** [comment]
OK, so that's the error that I saw above. For me, the fix was to run `pub get` (so you probably want to run `flutter pub get`) in the package I wanted to run DCDG against before running it. This is so that the analyzer can find your package's dependencies and parse them.

**Comment by Nicolaidam** [comment]
Thank for your quick reply. 

It doesnt work for me even though I run flutter pub get in the pack.
I get the following: 
Nicolais-MacBook-Pro:models nicolai$ flutter pub global run dcdg
Error: No Dart package found at .
pub finished with exit code 1

**Comment by glesica** [comment]
Are you running it in the same directory as your Dart package? You have to point it at the directory that contains your `pubspec.yaml`.

**Comment by glesica** [comment]
Closing because the original problem should no longer be an issue with the latest release.

**Comment by Nicolaidam** [comment]
> Are you running it in the same directory as your Dart package? You have to point it at the directory that contains your `pubspec.yaml`.

yes I run it from lib folder, where i have the main.dart file that i want to make the diagram for.

This what I've done so far:
1) Added dcdg: ^2.0.1 to pupspec.yaml
2) Import in dart file i want to make a diagram for, in my case the main.dart in lib folder: import 'package:dcdg/dcdg.dart';
3) Navigated to folder with dart file (in my case the lib folder) and executed: 
pub global run dcdg -p /Users/nicolai/Documents/acdc_flutter_app'

I've also tried executing
flutter pub global run dcdg -p /Users/nicolai/Documents/acdc_flutter_app/pubspec.yaml

Im still getting the error :(
Unhandled exception:
NoSuchMethodError: The method 'accept' was called on null.
Receiver: null

**Comment by glesica** [comment]
You don't need to import it into your code, nor do you need to add it as a dependency to your project. You can't run it from the `lib/` directory. You run it from your package directory (the one with the `pubspec.yaml` file in it, as I've said earlier and as can be seen in the examples). Here's an example. This is a copy-paste of a terminal session on my machine:

```
dcdg.dart on  master [?]
➜ pub global activate dcdg
Package dcdg is currently active at version 3.0.0.
Resolving dependencies...
The package dcdg is already activated at newest available version.
To recompile executables, first run `global decativate dcdg`.
Installed executable dcdg.
Activated dcdg 3.0.0.

dcdg.dart on  master [?]
➜ ls
CHANGELOG.md          ROADMAP               build                 pubspec.lock
Dockerfile_build      USAGE.txt             diagram.puml          pubspec.yaml
LICENSE               analysis_options.yaml example               test
README.md             bin                   lib                   tool

dcdg.dart on  master [?]
➜ pub global run dcdg -o diagram.puml
```

Beyond that, I'm not sure how else I can help you. Sorry.

**Comment by Nicolaidam** [comment]
Ahhh i think i have the problem. When i run "flutter pub global activate dcdg" i get this warning:
![image](https://user-images.githubusercontent.com/32563707/111395727-ceb76b00-86bd-11eb-9aea-9895566c9366.png)
So the the pub is installed in $HOME/Documents/flutter/.pub-cache/bin, and thats the reason why i get the error "NoSuchMethodError: The method 'accept' was called on null."

Will it help to add the path: export PATH="$PATH":"$HOME/Documents/flutter/.pub-cache/bin"
to .bashrc? Im not really familiar with this way of using the mac terminal yet

Thank you so much!
